name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/determinate-nix-action@v3.6.5

    - name: Prepare Nix deps
      run: nix-shell --run "bb --version"

    - name: Prepare Clojure deps
      run: nix-shell --run "clojure -P -M:test"

    - name: Install b3-strace-parser
      run: nix-shell --run "bb compile-strace-parser"

    - name: Run tests
      run: nix-shell --run "bb test:once"
